version: '3'
services:
  wukong-provider:
    image: "wukong-provider:1.0"
    restart: always
    build: wukong-provider
    volumes:
      - /opt/wukong/logs:/opt/wukong/logs
    ports:
      - 8082:8082
    container_name: wukong-provider

  wukong-consumer:
    image: "wukong-consumer:1.0"
    restart: always
    build: wukong-consumer
    ports:
      - 8081:8081
    volumes:
      - /opt/wukong/logs:/opt/wukong/logs
    container_name: wukong-consumer

  wukong-scripture:
    image: "wukong-scripture:1.0"
    restart: always
    build: wukong-scripture
    ports:
      - 8083:8083
    volumes:
      - /opt/wukong/logs:/opt/wukong/logs
    container_name: wukong-scripture

  xxl-job-admin:
    image: "xxl-job-admin:2.1.2"
    restart: always
    build: xxl-job-admin
    ports:
      - 8080:8080
    volumes:
      - /opt/wukong/logs:/opt/wukong/logs
    container_name: xxl-job-admin

  athena-fronted:
    image: "nginx:latest"
    restart: always
    volumes:
      - /opt/wukong/athena-fronted/www:/usr/share/nginx/html:ro
      - /opt/wukong/athena-fronted/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    container_name: athena-fronted    
