version: '3'
services:
  mysql-server:
    image: "mysql-server:forever"
    restart: always
    build: wukong-database/
    ports:
      - 3307:3306
    volumes:
      - /opt/wukong/mysql/data:/var/lib/mysql
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: 123456
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
    container_name: mysql-server


